name: 07 - expressions
run-name: 07 - expression | Debug ${{ inputs.debug && 'ON' || 'OFF'}}


on: 
   #  push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print start-up'
              # if: ${{ inputs.debug }} this also works
              if: inputs.debug 
              run: |
                echo "Triggered by ${{ github.event_name}}"
                echo "sha code: ${{ github.sha}}"
                echo "branch: ${{ github.ref}}"
                echo "runner: ${{ runner.os}}"

            - name: '[debug] print when triggered by main'
              # if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}    
              if: inputs.debug && github.ref == 'refs/heads/main' 
              run: echo "I was triggered from main"
            
            - name: 'Some bread'
              run: echo "hungry, some bread!"

